# Vectors

TRY IT! Create a row vector and column vector, and show the shape of the vectors.

In [1]:
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


TRY IT! Transpose the row vector we defined above into a column vector and calculate the 𝐿1, 𝐿2, and 𝐿∞ norm of it. Verify that the 𝐿∞ norm of a vector is equivalent to the maximum value of the elements in the vector.

In [4]:
from numpy.linalg import norm
new_vector = vector_row.T
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


The dot product of two vectors is the sum of the product of the respective elements in each vector and is denoted by ⋅. v⋅w is read “v dot w.” The angle between two vectors, θ, is defined by the formula: 𝑣⋅𝑤=‖𝑣‖2‖𝑤‖2cos𝜃. 

TRY IT! Compute the angle between the vectors 𝑣=[10,9,3] and 𝑤=[2,5,12]

In [5]:
from numpy import arccos, dot

v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]


Finally, the cross product between two vectors, 𝑣 and 𝑤, is written 𝑣×𝑤. It is defined by 𝑣×𝑤=‖𝑣‖2‖𝑤‖2sin(𝜃)n, where 𝜃 is the angle between the 𝑣 and 𝑤(which can be computed from the dot product) and 𝑛 is a vector perpendicular to both 𝑣 and 𝑤 with unit length (i.e., the length is one). The geometric interpretation of the cross product is a vector perpendicular to both 𝑣 and 𝑤 with length equal to the area enclosed by the parallelogram created by the two vectors.

TRY IT! Given the vectors 𝑣=[0,2,0]and 𝑤=[3,0,0], use the Numpy function cross to compute the cross product of v and w.

In [6]:
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


TRY IT! Given the row vectors 𝑣=[0,3,2], 𝑤=[4,1,1], and 𝑢=[0,−2,0], write the vector 𝑥=[−8,−1,4] as a linear combination of 𝑣, 𝑤, and 𝑢.

In [7]:
v = np.array([[0, 3, 2]])
w = np.array([[4, 1, 1]])
u = np.array([[0, -2, 0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


# Matrices